name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      # - name: Run tests
      #   run: npm test

      - name: Archive production artifacts
        run: tar -czf app.tar.gz .

      - name: Upload artifact
        uses: actions/upload-artifact@v4     # ✅ NEW VERSION
        with:
          name: football_app
          path: app.tar.gz
